proxies:
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HK(æ¨è)
  server: hk.de180997-0810-4174-8f14-eb8d79d47a0c.4c8f0b93.demo-chat-airport.com
  port: 56892
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HK(å¤‡ç”¨)
  server: hkv6.de180997-0810-4174-8f14-eb8d79d47a0c.4612afe1.demo-chat-airport.com
  port: 11371
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: â‡ï¸ç™½ç¾Šåº§-BGP(æ¨è)
  server: hkv6a.de180997-0810-4174-8f14-eb8d79d47a0c.a5e6e977.demo-chat-airport.com
  port: 56882
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: â‡ï¸ç™½ç¾Šåº§-BGP(å¤‡ç”¨)
  server: hkv6b.de180997-0810-4174-8f14-eb8d79d47a0c.7cc0aa7a.demo-chat-airport.com
  port: 56882
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: vmess
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKA(ä¸‹è½½)
  server: cos-cdn-a.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKB(ä¸‹è½½)
  server: cos-cdn-b.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡»ğŸ‡³ç™½ç¾Šåº§-VNA(ä¸‹è½½)
  server: cos-cdn-c.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡»ğŸ‡³ç™½ç¾Šåº§-VNB(ä¸‹è½½)
  server: cos-cdn-d.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JP(æ¨è)
  server: jp.539bb8de-73bb-4398-8c9b-d145a8901e8f.5201a354.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JP(å¤‡ç”¨)
  server: jpv6.539bb8de-73bb-4398-8c9b-d145a8901e8f.5e63934c.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SG(æ¨è)
  server: sg.173a00e1-f7e7-4018-9d07-3850d2ca48ad.ba93f54e.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SG(å¤‡ç”¨)
  server: sgv6.173a00e1-f7e7-4018-9d07-3850d2ca48ad.a5c38186.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KR(æ¨è)
  server: kr.91b30040-0142-4050-a005-142dc68a5ba8.e0fb388f.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KR(å¤‡ç”¨)
  server: krv6.91b30040-0142-4050-a005-142dc68a5ba8.e7a04f93.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¹ğŸ‡¼ç™½ç¾Šåº§-TW(æ¨è)
  server: twa.8b437e21-4951-49e6-9587-3a4be48e9e30.902d52f1.demo-chat-airport.com
  port: 16890
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¹ğŸ‡¼ç™½ç¾Šåº§-TW(å¤‡ç”¨)
  server: twb.8b437e21-4951-49e6-9587-3a4be48e9e30.490b11fc.demo-chat-airport.com
  port: 16891
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKA
  server: hka.de180997-0810-4174-8f14-eb8d79d47a0c.2cca423a.demo-chat-airport.com
  port: 56892
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKB
  server: hkb.de180997-0810-4174-8f14-eb8d79d47a0c.f5ec0137.demo-chat-airport.com
  port: 56892
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKC
  server: hkc.de180997-0810-4174-8f14-eb8d79d47a0c.42f1c033.demo-chat-airport.com
  port: 11371
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡­ğŸ‡°ç™½ç¾Šåº§-HKD
  server: hkd.de180997-0810-4174-8f14-eb8d79d47a0c.47a1872d.demo-chat-airport.com
  port: 11371
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡ºğŸ‡¸ç™½ç¾Šåº§-USA
  server: usa.e974c2d6-0b71-4913-931a-4d38f58a71fc.bea0aeb5.demo-chat-airport.com
  port: 56770
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡ºğŸ‡¸ç™½ç¾Šåº§-USB
  server: usb.e974c2d6-0b71-4913-931a-4d38f58a71fc.6786edb8.demo-chat-airport.com
  port: 56770
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡ºğŸ‡¸ç™½ç¾Šåº§-USC
  server: usc.e974c2d6-0b71-4913-931a-4d38f58a71fc.d09b2cbc.demo-chat-airport.com
  port: 56771
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡ºğŸ‡¸ç™½ç¾Šåº§-USD
  server: usd.e974c2d6-0b71-4913-931a-4d38f58a71fc.d5cb6ba2.demo-chat-airport.com
  port: 56771
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¦ğŸ‡ºç™½ç¾Šåº§-AUA
  server: aua.82fe8230-813e-4b73-9160-e1450a03d3c4.7465904a.demo-chat-airport.com
  port: 56772
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¦ğŸ‡ºç™½ç¾Šåº§-AUB
  server: aub.82fe8230-813e-4b73-9160-e1450a03d3c4.ad43d347.demo-chat-airport.com
  port: 56773
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SGA
  server: sga.173a00e1-f7e7-4018-9d07-3850d2ca48ad.16f108e4.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SGB
  server: sgb.173a00e1-f7e7-4018-9d07-3850d2ca48ad.cfd74be9.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SGC
  server: sgc.173a00e1-f7e7-4018-9d07-3850d2ca48ad.78ca8aed.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SGD
  server: sgd.173a00e1-f7e7-4018-9d07-3850d2ca48ad.7d9acdf3.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¸ğŸ‡¬ç™½ç¾Šåº§-SGE
  server: sge.173a00e1-f7e7-4018-9d07-3850d2ca48ad.ca870cf7.demo-chat-airport.com
  port: 56893
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JPA
  server: jpa.539bb8de-73bb-4398-8c9b-d145a8901e8f.b01401d1.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JPB
  server: jpb.539bb8de-73bb-4398-8c9b-d145a8901e8f.693242dc.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JPC
  server: jpc.539bb8de-73bb-4398-8c9b-d145a8901e8f.de2f83d8.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JPD
  server: jpd.539bb8de-73bb-4398-8c9b-d145a8901e8f.db7fc4c6.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¯ğŸ‡µç™½ç¾Šåº§-JPE
  server: jpe.539bb8de-73bb-4398-8c9b-d145a8901e8f.6c6205c2.demo-chat-airport.com
  port: 56894
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KRA
  server: kra.91b30040-0142-4050-a005-142dc68a5ba8.38262b70.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KRB
  server: krb.91b30040-0142-4050-a005-142dc68a5ba8.e100687d.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KRC
  server: krc.91b30040-0142-4050-a005-142dc68a5ba8.561da979.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KRD
  server: krd.91b30040-0142-4050-a005-142dc68a5ba8.534dee67.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡°ğŸ‡·ç™½ç¾Šåº§-KRE
  server: kre.91b30040-0142-4050-a005-142dc68a5ba8.e4502f63.demo-chat-airport.com
  port: 56895
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¦ğŸ‡·ç™½ç¾Šåº§-ARA
  server: agta.3b7b2d71-de6d-49f9-b2f3-8c94c20cc9b7.d2a3ad0b.demo-chat-airport.com
  port: 62250
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: hysteria2
  name: ğŸ‡¦ğŸ‡·ç™½ç¾Šåº§-ARB
  server: agtav6.3b7b2d71-de6d-49f9-b2f3-8c94c20cc9b7.619c35de.demo-chat-airport.com
  port: 62250
  password: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šA
  server: cos-cdn-c.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šB
  server: cos-cdn-d.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šC
  server: cos-cdn-e.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šD
  server: cos-cdn-f.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šE
  server: cos-cdn-a.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šF
  server: cos-cdn-b.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šG
  server: cos-cdn-c.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šH
  server: cos-cdn-d.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šI
  server: cos-cdn-e.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šJ
  server: cos-cdn-f.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šK
  server: cos-cdn-a.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šL
  server: cos-cdn-b.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šM
  server: cos-cdn-c.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šN
  server: cos-cdn-d.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡­ğŸ‡°HK-ç§»åŠ¨è”é€šO
  server: cos-cdn-e.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USA
  server: cos-cdn-g.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USA/Z
  server: cos-cdn-h.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USB
  server: cos-cdn-i.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USB/Z
  server: cos-cdn-j.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USC
  server: cos-cdn-k.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USC/Z
  server: cos-cdn-l.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USD
  server: cos-cdn-g.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USD/Z
  server: cos-cdn-h.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USE
  server: cos-cdn-i.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USE/Z
  server: cos-cdn-j.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USF
  server: cos-cdn-k.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USF/Z
  server: cos-cdn-l.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USG
  server: cos-cdn-g.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USG/Z
  server: cos-cdn-h.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USH
  server: cos-cdn-i.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USH/Z
  server: cos-cdn-j.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USI
  server: cos-cdn-k.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
- type: vmess
  name: ğŸ‡ºğŸ‡¸ç”µä¿¡ä¸“ç”¨/USI/Z
  server: cos-cdn-l.alicdn.win
  port: 443
  uuid: d89224d4-6ca2-4f7f-b271-4b9fc05ed54a
  alterId: 0
  cipher: auto
proxy-groups: []
rules: []
